### PR TITLE
Allow using the meta "schemaName" property to override schema

### PR DESCRIPTION
**Pull request by keeganmccallum**

### CODE REVIEW

**Comment by tjwebb** [comment]
Awesome @keeganmccallum! Thanks for the PR. This closes #18?

**Comment by keeganmccallum** [comment]
Yup! No problem!

**Comment by keeganmccallum** [comment]
Hey @tjwebb, I was just interested in if there are any changes you would like me to make to try and get this merged, and if not, what the kind of release schedule tends to be for this project. My team wants to release a new application using this functionality and would prefer to run off of the official repo vs my fork.

**Comment by tjwebb** [comment]
@keeganmccallum sure thing, I must have missed your last comment. If your team has an interest in helping maintain the project, are you interested in joining as a collaborator?

**Comment by keeganmccallum** [comment]
Yeah I would be interested!

**Pull request merged**
